### PR TITLE
Update OSRM.Locale.it.js

### PR DESCRIPTION
**Pull request by sabas**

### CODE REVIEW

**Comment by DennisSchiefer** [comment]
Thanks for the update.

**Comment by DennisSchiefer** [comment]
but you really should make the pull request against the develop branch - I forgot to check and now merged against master, which will bring some woes later on.

**Comment by sabas** [comment]
Oops, sorry, didn't see the different branch.. Should I make another pull request?

**Comment by DennisSchiefer** [comment]
no, not required. I already merged it with the develop branch and uploaded it.

**Comment by sabas** [comment]
Thanks !

**Pull request merged**
