### PR TITLE
additions to make web client compatible to new JSON generator component

### PR DESCRIPTION
**Pull request by DennisOSRM**
currently a new JSON generator is under development for the backend (slated for release on Monday). It brings two important functional differences to the output:
- fields that are empty are omitted
- `"alternative_found": True/False` now indicates if an alternative route has been found.

The patch is backward compatible, i.e. it will work with the current JSON generator and also the new one.

### CODE REVIEW

**Comment by DennisOSRM** [comment]
Found a bug, will be updating the PR in a little while.

**Comment by DennisOSRM** [comment]
@DennisSchiefer I have updated the PR. It should now work _alright_ with the new JSON generator of the backend. The main issue is that empty fields in JSON are not printed anymore but the client relies on having them.

**Comment by DennisSchiefer** [comment]
Does this only occur for the alternative paths you have patched or are there other fields that could be regularly missing? If yes, that might be a nightmare to fix.

I wonder whether the client can easily have a default data structure with all fields and the JSON response only fills out the values. But until Whitsun I cannot take care of that.

**Comment by DennisOSRM** [comment]
> Does this only occur for the alternative paths you have patched or are there other fields that could be regularly missing? If yes, that might be a nightmare to fix.

It _should_ only happen for the alternative route in the queries that UI does. But I didn't test it explicitly.

> I wonder whether the client can easily have a default data structure with all fields and the JSON response only fills out the values. But until Whitsun I cannot take care of that.

One could initialize such a data structure and reset it when new data comes in.

**Pull request merged**
