### PR TITLE
Adjust zoom to see the whole route after computation

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by DennisSchiefer** [comment]
We probably won't add this request in its current form as we think it yields a very unintuitive behaviour in combination with dragging routes or creating a route by clicking on the map. But when used together with searching for a start/target location, it might be a good addition.

**Comment by raphink** [comment]
Right. I agree that it should probably only be triggered when start/end points are changed.

**Comment by DennisSchiefer** [comment]
Today I had some time to play around with this option. And by now I think, it would be better left out or moved to an extra zoom button. The reason for this is, I got very frustrated when I typed in a town name and pressed return and saw the complete route displayed but to move the marker to the exact street I wanted to go, I had to zoom in again to drag the marker accurately.

I realize a zoom-to-route button would be a clunky solution, but right now, I have no better ideas.

**Comment by emiltin** [comment]
i don't think a zoom-to-route button (or fit-to-route) button is clunky.
there's nothing worse than solutions that are too automatic, and thus confusing.

**Comment by raphink** [comment]
> i don't think a zoom-to-route button (or fit-to-route) button is clunky.
> there's nothing worse than solutions that are too automatic, and thus
> confusing.
> 
> I think so, too, although I think this feature could still be used when
> points are setup using the search boxes, but not when points are added
> directly on the map.

**Comment by DennisSchiefer** [comment]
I have now added a zoom-on-route button between the reset and reverse buttons in my local implementation. After seeing it in action, I think it is an okay solution.

Regarding zooming when points are set using the search boxes: Initially I also thought, this would be a good idea. But then when actually started to use it his way, I found myself zooming in again to move the marker on the exact location I wanted to start/end. Thus, I think it is not a really a good solution.

**Comment by DennisSchiefer** [comment]
The zoom button is now in the develop branch. Thus, I am closing this request for now.

**Pull request closed without merging**
