### PR TITLE
Italian Localization

### PR DESCRIPTION
**Pull request by sabas**
I've translated the english language file in Italian.

### CODE REVIEW

**Comment by sabas** [comment]
PS I've forked the master branch and I've committed to the develop branch, but shows also other edits. Should I commit directly to master?

**Comment by emiltin** [comment]
what i found to be best is to checkout the latest master to a new branch (giving it a descriptive name like 'italian_localization'), and then commit to that, and send the pull request from that branch. that way each pull request is isolated and easy to read.

**Comment by DennisSchiefer** [comment]
emiltin is right. This is usually the preferred workflow - especially for larger contributions. For single file contributions I usually simply copy the file myself.

The reason why you are seeing the other edits is because I made a failure when last commiting a small bug fix. I commited directly to master instead of develop. Thus, the commits you see are what is in master but not in develop.

I will put the Italian translation online later that week with a new release.

**Comment by sabas** [comment]
Thanks!

**Pull request closed without merging**
