### PR TITLE
Add icons to place picker

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by DennisSchiefer** [comment]
Thank you for the effort on this. The basic idea is very nice, but I think it is not really needed in this context - simply searching for cities/streets. When implementing a full-featured POI search, it might become more interesting. Also, in my testings most of the search results by Nominatim had a category for which no image was displayed (e.g. search for "London").

A further note: The number of icons seems to be a bit excessive for the required task.

**Comment by raphink** [comment]
> Thank you for the effort on this. The basic idea is very nice, but I think
> it is not really needed in this context - simply searching for
> cities/streets.

Well, that depends. Sometimes, there's more than one place that matches the
search, and it's useful to know if it's a city/town/amenity easily.

Actually, I think the search is still not very useful this way. The list is
only provided for the start point, and not for the end point since the
route is automatically calculated. I think it would be nicer to use this as
a drop select div which refreshes as the user types, instead of using the
information box for that. A the user would begin typing a word in the start
field, a selection drop menu would show up with icons, and he could select
the proper entry from it. The same would go for the end point.

> When implementing a full-featured POI search, it might become more
> interesting. Also, in my testings most of the search results by Nominatim
> had a category for which no image was displayed (e.g. search for "London").

That's true, but the CSS settings I have give a default icon to all entries
(the little house) so no entry should be icon-less.

> A further note: The number of icons seems to be a bit excessive for the
> required task.

Right, I just copied the whole set and began assigning them as I saw more
results coming up, the idea being to eventually map them all (or as many as
possible)

**Comment by DennisSchiefer** [comment]
Regarding the improvement of the search boxes:
I agree, an updating pulldown box would be a good feature [even though I personally hate this feature in any application I see it, but this is just my personal preference and not what most people want]. We will implement this feature when we eventually make the move to JQuery (and GUI version 0.2.x), as it has good support for such pulldown boxes - I assume that Nominatim also supports this with little lag for its answers.
BTW: The decision to display the search results in the information box and automatically compute the route when the second point is entered was originally made, because it was the same behaviour as on a big routing site.

Regarding the default icon:
Hm strange. I checked out your branch /dev/icons and started testing with your own code base. And for many entries I don't see any picture.

**Comment by DennisSchiefer** [comment]
I have started a new branch trial/geocoder, you might want to look into. It uses the icons provided by Nominatim, outputs the type/class information and has built-in options for filtering / sorting (though I didn't bother to find good sorting criteria - see pull request #6).

**Comment by DennisSchiefer** [comment]
closing this request as it is by now implemented

**Pull request closed without merging**
